# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Code_Exercise_Telstra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Code_Exercise_Telstra
   pod 'SDWebImage', '~> 5.0'

end
